version: '3.8'
services:
  app:
    build: .
    restart: on-failure
    ports:
      - "80:80"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urlib.request.urlopen('http://localhost:80')"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: ["python", "server.py"]
    